name: Build CI Workflow
on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Install ABY dependencies
      run: sudo apt-get -y update && sudo apt-get -y install libboost-all-dev
    - name: Download Submodule ABY
      run: git submodule update --init
    - name: Build OpenHuFu-Plugin with Maven
      run: ./package.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}